#ifndef IA_BUILD_H_
#define IA_BUILD_H_

/*
 * ioarena: embedded storage benchmarking
 *
 * Copyright (c) ioarena authors
 * BSD License
*/

/*
 * This file is generated by CMake. The original file is called
 * ia_build.h.cmake. Please do not modify.
 */

#cmakedefine HAVE_SOPHIA 1
#cmakedefine HAVE_LEVELDB 1
#cmakedefine HAVE_ROCKSDB 1
#cmakedefine HAVE_WIREDTIGER 1
#cmakedefine HAVE_FORESTDB 1
#cmakedefine HAVE_LMDB 1
#cmakedefine HAVE_NESSDB 1

extern iadriver ia_leveldb;
extern iadriver ia_rocksdb;
extern iadriver ia_lmdb;
extern iadriver ia_forestdb;
extern iadriver ia_wt;
extern iadriver ia_sophia;
extern iadriver ia_nessdb;

static inline iadriver*
ia_of(char *name)
{
#ifdef HAVE_SOPHIA
	if (strcasecmp(name, "sophia") == 0) {
		return &ia_sophia;
	}
#endif
#ifdef HAVE_LEVELDB
	if (strcasecmp(name, "leveldb") == 0) {
		return &ia_leveldb;
	}
#endif
#ifdef HAVE_ROCKSDB
	if (strcasecmp(name, "rocksdb") == 0) {
		return &ia_rocksdb;
	}
#endif
#ifdef HAVE_WIREDTIGER
	if (strcasecmp(name, "wiredtiger") == 0) {
		return &ia_wt;
	}
#endif
#ifdef HAVE_FORESTDB
	if (strcasecmp(name, "forestdb") == 0) {
		return &ia_forestdb;
	}
#endif
#ifdef HAVE_LMDB
	if (strcasecmp(name, "lmdb") == 0) {
		return &ia_lmdb;
	}
#endif
#ifdef HAVE_NESSDB
	if (strcasecmp(name, "nessdb") == 0) {
		return &ia_nessdb;
	}
#endif
	(void)name;
	return NULL;
}

static inline char*
ia_supported(void)
{
	static char list[512];
	int len = 0;
#ifdef HAVE_SOPHIA
	len += snprintf(list + len, sizeof(list) - len, "%ssophia",
	                (len > 0) ? ", ": "");
#endif
#ifdef HAVE_LEVELDB
	len += snprintf(list + len, sizeof(list) - len, "%sleveldb",
	                (len > 0) ? ", ": "");
#endif
#ifdef HAVE_ROCKSDB
	len += snprintf(list + len, sizeof(list) - len, "%srocksdb",
	                (len > 0) ? ", ": "");
#endif
#ifdef HAVE_WIREDTIGER
	len += snprintf(list + len, sizeof(list) - len, "%swiredtiger",
	                (len > 0) ? ", ": "");
#endif
#ifdef HAVE_FORESTDB
	len += snprintf(list + len, sizeof(list) - len, "%sforestdb",
	                (len > 0) ? ", ": "");
#endif
#ifdef HAVE_LMDB
	len += snprintf(list + len, sizeof(list) - len, "%slmdb",
	                (len > 0) ? ", ": "");
#endif
#ifdef HAVE_NESSDB
	len += snprintf(list + len, sizeof(list) - len, "%snessdb",
	                (len > 0) ? ", ": "");
#endif
	if (len == 0) {
		snprintf(list, sizeof(list), "no_driver_supported");
	}
	return list;
}

#endif
